# Generated by Django 5.2.15 on 2026-07-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.CharField(max_length=30)),
                ('pname', models.CharField()),
                ('pimg', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('files', models.FileField(blank=True, null=True, upload_to='files/')),
            ],
        ),
    ]
